# Generated by Django 6.0 on 2025-12-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mensagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='data_envio',
            new_name='criado_em',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='lido',
        ),
    ]
