# Generated by Django 6.0 on 2025-12-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_data_envio_mensagem_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='lido',
            field=models.BooleanField(default=False),
        ),
    ]
